project:
  type: website

website:
  title: "Jake Gehri"
  navbar:
    background: primary
    search: true
    right:
      - text: "Home"
        file: index.qmd
      - projects.qmd
      - blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



