project:
  type: website
  resources:
    - Jake Gehri CV v_22.10.19.pdf

website:
  title: "Jake Gehri"
  site-url: https://jakegehri.github.io
  navbar:
    background: primary
    search: true
    right:
      - text: "Home"
        file: index.qmd
      - projects.qmd
      - blog.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true
